services:
  - type: web
    name: banking-api
    env: docker
    plan: free

    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar app.jar"

    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-nameless-base-alnzwruy-pooler.c-3.eu-central-1.aws.neon.tech/neondb?sslmode=require

      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner

      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_QHu2joOR8WJi